### ISSUE TITLE
lfs wrapping

### ISSUE THREAD

**Issue by sonoro1234** [luapower/fs#2]
Working on a wrapper to provide an interface for lfs as previously did in https://github.com/sonoro1234/luafilesystem

-unixperms is a dependence not mentioned in https://luapower.com/fs
-file permissions not available in windows (would it be possible?)

The wapping is done as this:
-all necessary luapower modules are in lua/luapower folder
-lfs.lua file is:

```lua
local sep = package.config:sub(1,1)
local currpath = debug.getinfo(1,'S').source:match("@(.+)"..sep.."([^"..sep.."]+)")
package.path = currpath..sep.."luapower"..sep.."?.lua;"..package.path


local lfs = require"fs"
local function attrtranslate(t)
	t.mode = t.type
	if t.mode == "dir" then t.mode = "directory" end
	return t
end

lfs.currentdir = lfs.cd
lfs.attributes = function(...) return attrtranslate(lfs.attr(...,false)) end
lfs.symlinkattributes = function(...) return attrtranslate(lfs.attr(...,true)) end
lfs.link = mksymlink
local oldfs_dir = lfs.dir
lfs.dir = function(path) return oldfs_dir(path,true) end
return lfs
```

**Comment by capr** [comment]
Sorry about the dependencies not showing up correctly. They're currently a bit messed up from the fact that 32bit platform support was removed and the addition of nginx as a runtime, an integration which I haven't finished yet.

Anyway unixperms is a "runtime dependency", i.e. the module is only required if you actually need to parse any permission strings. If you go to the info tab of the package you will see it listed as such (I just pused a fix related to that btw).

Windows permissions were not implemented. Feel free to add them, I personally didn't find it a priority and they're a bit hard to add with those security descriptors and all.

Anyway, what do you want me to do with this compatibility layer? Do you want it to be added to luapower? If so, all you have to do is make a repo with lfs.lua and lfs.md in it, and I'll add a `lfs.origin` file to https://github.com/luapower/luapower-repos/tree/master/.mgit and it will show up on the website (but you'd have to remove the first 3 lines).

**Comment by sonoro1234** [comment]
To implement file permissions as lfs does I have readen stat.cpp in MSVC distribution, It uses GetFileInformationByHandleEx to get FileBasicInfo, then from basic_info.FileAttributes just look to FILE_ATTRIBUTE_READONLY (so it will be rw or r-). It then looks if filename ends with exe,cmd,bat or com to say it is executable. Group and other fields are copied from what we already have.

It is quite limited, so may be it is not what you would want in your library, isn't it?

**Comment by capr** [comment]
These are not permissions, these are attributes (inherited from the DOS days) and are already supported.

**Comment by sonoro1234** [comment]
But perms are not provided by fs.attr in windows

**Comment by capr** [comment]
Sorry I don't understand. What perms are not provided?

**Comment by sonoro1234** [comment]
```lua
{
        ["mtime"]=1575114106.8659
        ["atime"]=1575216522.6826
        ["archive"]=true
        ["btime"]=1487837218.1617
        ["nlink"]=1
        ["id"]=12384898975650603ULL
        ["size"]=2
        ["type"]="file"
        ["volume"]=405772402
        ["ctime"]=1575138564.2145
        ["not_indexed"]=true}
```
Are all the attributes provided in windows by fs.attr
In fs description it is saying that perms is also provided on linux and macos https://luapower.com/fs#file-attributes

**Comment by sonoro1234** [comment]
But having the readonly attribute and the filename I can emulate stat behaviour in lfs.

**Comment by capr** [comment]
Yes that is correct. And if I understand you correctly, you want the `perms` field to show `r` when `readonly` field is `true` on Windows and otherwise show `rw`, is that right?

My point was that I already use GetFileInformationByHandleEx and FileBasicInfo to get that information just like lfs does (look at the code), only that I'm not populating the `perms` field on Windows, but the `readonly` field, and the reason for that is that since the security models are so different between Windows and Linux, I'm not sure that you can even talk about a cross-platform `perms` field, but sure, in the case of the read-only bit, they are indeed somewhat alike.

**Comment by sonoro1234** [comment]
>  Do you want it to be added to luapower?

Not necesarilly, you can do as you like.
This is the state of the wrapping
```lua
local sep = package.config:sub(1,1)
local currpath = debug.getinfo(1,'S').source:match("@(.+)"..sep.."([^"..sep.."]+)")
package.path = currpath..sep.."luapower"..sep.."?.lua;"..package.path


local lfs = require"fs"
local function attrtranslate(name,t)
	t.mode = t.type
	if t.mode == "dir" then t.mode = "directory" end
	t.type = nil
	--permissions
	if t.perms then
		t.permissions = t.perms
		t.perms = nil
	else --windows
		local endname = name:match"%.exe$" or name:match"%.bat$"  or name:match"%.cmd$"  or name:match"%.com$"
		local perms = "r"..(t.readonly and "-" or "w")..(endname and "x" or "-")
		perms = perms:rep(3)
		t.permissions = perms
		t.readonly = nil
		t.archive = nil
	end
	return t
end

lfs.currentdir = lfs.cd
lfs.attributes = function(fname,...) return attrtranslate(fname,lfs.attr(fname,...,false)) end
lfs.symlinkattributes = function(fname,...) return attrtranslate(fname,lfs.attr(fname,...,true)) end
lfs.link = mksymlink
lfs.rmdir = lfs.remove
local oldfs_dir = lfs.dir
lfs.dir = function(path) return oldfs_dir(path,true) end
return lfs
```
