### ISSUE TITLE
dangling pointer?

### ISSUE THREAD

**Issue by sonoro1234** [luapower/fs#3]
Hi,

In line https://github.com/luapower/fs/blob/master/fs_posix.lua#L840 a `DIR *` is returned, as it is only attached to a cdata it could be eventually garbage collected.  Wouldnt it be a problem? What will be `dir._dirp` then?

**Comment by capr** [comment]
The gc doesn't know about cdata unless you call ffi.gc() yourself to track it, so it shouldn't be a problem in this case.

**Comment by sonoro1234** [comment]
Thanks for answering.

It cames from a previous question: https://github.com/spacewander/luafilesystem/issues/9

I answered myself, I expect it was correct.

**Comment by sonoro1234** [comment]
Thanks
